<a href="https://colab.research.google.com/github/harunbansode/Pandas00/blob/main/Pandas00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]], columns=['A', 'B', 'C'])

In [3]:
df.head()

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [4]:
df.shape

(3, 3)

**Head is used for Top to Bottom**

In [5]:
df.head(1)

   A  B  C
0  1  2  3

In [6]:
df.head(2)

   A  B  C
0  1  2  3
1  4  5  6

In [7]:
df.head(3)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

**Tail is used for Bottom to Top**

In [8]:
df.tail(1)

   A  B  C
2  7  8  9

In [9]:
df.tail(2)

   A  B  C
1  4  5  6
2  7  8  9

In [10]:
df.tail(3)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

**For Headers**

In [11]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [12]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [13]:
df.index.tolist()

[0, 1, 2]

**Setting up default index**

In [14]:
df = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]], columns=['A', 'B', 'C'], index=['x', 'y', 'z'])

In [15]:
df

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [16]:
df.index

Index(['x', 'y', 'z'], dtype='object')

In [17]:
df.index.tolist()

['x', 'y', 'z']

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 204.0+ bytes

In [19]:
df.describe()

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [20]:
df.nunique()

A    3
B    3
C    3
dtype: int64

In [21]:
df['A'].nunique()

3

In [22]:
df.size

9

In [121]:
coffee = pd.read_csv('/coffee.csv')

In [24]:
# chai = pd.read_csv('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/warmup-data/coffee.csv')

In [25]:
# chai

In [122]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [27]:
results = pd.read_parquet('/results.parquet')

In [28]:
results

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,17.0,True,None
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,None
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,32.0,True,None
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,None
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,None
...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,None,26.0,False,None
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,None,28.0,False,None
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,None
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,None,NaN,False,None
308407,2022.0,Winter,None,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,None,None,24.0,False,None

In [29]:
results.columns.tolist()

['year',
 'type',
 'discipline',
 'event',
 'as',
 'athlete_id',
 'noc',
 'team',
 'place',
 'tied',
 'medal']

In [30]:
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,17.0,True,None
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,None
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,32.0,True,None
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,None
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,None

In [31]:
olympics_data = pd.read_excel('/olympics-data.xlsx', sheet_name = "results")

In [32]:
olympics_data.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [33]:
bios = pd.read_csv('/bios.csv')

In [123]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [124]:
coffee.loc[[1, 2, 5]]

         Day Coffee Type  Units Sold
1     Monday       Latte          15
2    Tuesday    Espresso          30
5  Wednesday       Latte          25

In [137]:
coffee.loc[:, ['Day', 'Coffee Type']]

          Day Coffee Type
0      Monday    Espresso
1      Monday       Latte
2     Tuesday    Espresso
3     Tuesday       Latte
4   Wednesday    Espresso
5   Wednesday       Latte
6    Thursday    Espresso
7    Thursday       Latte
8      Friday    Espresso
9      Friday       Latte
10   Saturday    Espresso
11   Saturday       Latte
12     Sunday    Espresso
13     Sunday       Latte

In [138]:
coffee.loc[8:12, ['Day', 'Units Sold']]

         Day  Units Sold
8     Friday          45
9     Friday          35
10  Saturday          45
11  Saturday          35
12    Sunday          45

In [141]:
coffee.iloc[0:5, [0,2]]

         Day  Units Sold
0     Monday          25
1     Monday          15
2    Tuesday          30
3    Tuesday          20
4  Wednesday          35

In [38]:
# coffee.index = coffee['Day']

In [39]:
# coffee.loc[['Sunday', 'Saturday']]

In [142]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [41]:
# coffee.loc[1:4, 'Units Sold'] = 10

In [143]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [43]:
# coffee.iat[0,0]

In [44]:
# coffee.at[0, "Coffee Type"]

In [45]:
# coffee['Coffee Type']

In [145]:
coffee.sort_values('Coffee Type', ascending=True)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
2     Tuesday    Espresso          30
4   Wednesday    Espresso          35
6    Thursday    Espresso          40
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
1      Monday       Latte          15
3     Tuesday       Latte          20
5   Wednesday       Latte          25
7    Thursday       Latte          30
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35

In [146]:
coffee.sort_values(["Units Sold", "Coffee Type"], ascending=[0, 1])

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
2     Tuesday    Espresso          30
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
3     Tuesday       Latte          20
1      Monday       Latte          15

In [48]:
bios

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25
...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20

In [49]:
bios.loc[bios['height_cm'] > 215, ['name', 'born_city']]

                         name               born_city
5089       Viktor Pankrashkin         Moskva (Moscow)
5583     Paulinho Villas Boas               São Paulo
5673           Gunther Behnke              Leverkusen
5716                 Uwe Blab        München (Munich)
5781           Tommy Burleson               Crossnore
5796            Andy Campbell               Melbourne
6223              Lars Hansen  København (Copenhagen)
6270              Hu Zhangbao                     NaN
6409         Sergey Kovalenko                     NaN
6420            Jānis Krūmiņš                   Cēsis
6504              Luc Longley               Melbourne
6722         Shaquille O'Neal                  Newark
6937           David Robinson                Key West
6978          Arvydas Sabonis                  Kaunas
7074           Paulo da Silva               São Paulo
7188       Vladimir Tkachenko               Golovinka
7281         Stojko Vranković                   Drniš
7376      Eurelijus Žukauskas                Klaipėda
52608         Aleksey Kazakov      Naberezhnye Chelny
82100           Frédéric Weis              Thionville
89070                Yao Ming          Xuhui District
89075          Roberto Dueñas                  Madrid
107408       Peter John Ramos                 Fajardo
112312           Stanko Barać                  Mostar
112332    Andreas Glyniadakis                  Chania
112337          Hamed Haddadi                   Ahvaz
118663         Timofey Mozgov                     NaN
118676        Dmitry Musersky                Makiïvka
120266           Zhang Zhaoxu                 Binzhou
121694            Salah Mejri                Jendouba
123850         Tyson Chandler                 Hanford
130460               Li Muhao                 Guiyang
130461                Zhou Qi                Xinxiang
138671          Ondřej Balvín          Ústí nad Labem
139365         Moustapha Fall                   Paris

In [50]:
bios[bios['height_cm'] > 215][['name', 'born_city']]

                         name               born_city
5089       Viktor Pankrashkin         Moskva (Moscow)
5583     Paulinho Villas Boas               São Paulo
5673           Gunther Behnke              Leverkusen
5716                 Uwe Blab        München (Munich)
5781           Tommy Burleson               Crossnore
5796            Andy Campbell               Melbourne
6223              Lars Hansen  København (Copenhagen)
6270              Hu Zhangbao                     NaN
6409         Sergey Kovalenko                     NaN
6420            Jānis Krūmiņš                   Cēsis
6504              Luc Longley               Melbourne
6722         Shaquille O'Neal                  Newark
6937           David Robinson                Key West
6978          Arvydas Sabonis                  Kaunas
7074           Paulo da Silva               São Paulo
7188       Vladimir Tkachenko               Golovinka
7281         Stojko Vranković                   Drniš
7376      Eurelijus Žukauskas                Klaipėda
52608         Aleksey Kazakov      Naberezhnye Chelny
82100           Frédéric Weis              Thionville
89070                Yao Ming          Xuhui District
89075          Roberto Dueñas                  Madrid
107408       Peter John Ramos                 Fajardo
112312           Stanko Barać                  Mostar
112332    Andreas Glyniadakis                  Chania
112337          Hamed Haddadi                   Ahvaz
118663         Timofey Mozgov                     NaN
118676        Dmitry Musersky                Makiïvka
120266           Zhang Zhaoxu                 Binzhou
121694            Salah Mejri                Jendouba
123850         Tyson Chandler                 Hanford
130460               Li Muhao                 Guiyang
130461                Zhou Qi                Xinxiang
138671          Ondřej Balvín          Ústí nad Labem
139365         Moustapha Fall                   Paris

In [51]:
bios[(bios['height_cm'] > 215) & (bios['born_country'] == 'USA')]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN
6722,6755,Shaquille O'Neal,1972-03-06,Newark,New Jersey,USA,United States,216.0,137.0,NaN
6937,6972,David Robinson,1965-08-06,Key West,Florida,USA,United States,216.0,107.0,NaN
123850,126093,Tyson Chandler,1982-10-02,Hanford,California,USA,United States,216.0,107.0,NaN

In [52]:
bios[bios['name'].str.contains('harun|vivek', case=False)]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
19167,19302,Vivek Singh,1967-08-01,Varanasi,Uttar Pradesh,IND,India,176.0,59.0,2007-02-02
22593,22763,Harunobu Deno,1969-08-28,NaN,NaN,NaN,Japan,175.0,58.0,NaN
42798,43123,John Harun,1948-06-24,Machakos,Machakos,KEN,Kenya,184.0,80.0,NaN
48264,48617,Mika Haruna,1978-06-14,NaN,NaN,NaN,Japan,160.0,53.0,NaN
59884,60312,Harun Doğan,1976-01-01,Kahramanmaraş,Kahramanmaraş,TUR,Türkiye,165.0,58.0,NaN
63220,63690,Harun Ülman,1900-07-11,NaN,NaN,NaN,Türkiye,NaN,NaN,1977-01-26
93554,94306,Haruna Hosoya,1973-04-23,Kawanishi,Hyogo,JPN,Japan,158.0,50.0,NaN
116094,117475,Haruna Fukuoka,1984-01-25,Tokushima,Tokushima,JPN,Japan,156.0,48.0,NaN
119153,120939,Haruna Sakakibara,1994-03-11,Iyo,Ehime,JPN,Japan,182.0,73.0,NaN
125664,128009,Haruna Yoneyama,1991-11-07,Shizunai,Hokkaido,JPN,Japan,160.0,55.0,NaN
131609,134419,Ayyasamy Dharun,1996-12-31,Chinneripalayam,Tripura,IND,India,177.0,64.0,NaN
134374,137434,Haruna Ishikawa,1994-07-20,Kanazawa,Ishikawa,JPN,Japan,NaN,NaN,NaN
134417,137480,Haruna Matsumoto,1993-07-26,Sapporo,Hokkaido,JPN,Japan,157.0,52.0,NaN
137002,140238,Haruna Nagamori,2002-04-25,NaN,NaN,NaN,Japan,NaN,NaN,NaN
140849,144377,Haruno Sasaki,1995-02-26,NaN,NaN,NaN,Japan,172.0,68.0,NaN

In [53]:
bios[bios['born_country'].isin(['USA', 'GBR', 'FRA', 'TUR']) & (bios['name'].str.startswith('Harun'))]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
59884,60312,Harun Doğan,1976-01-01,Kahramanmaraş,Kahramanmaraş,TUR,Türkiye,165.0,58.0,NaN

In [54]:
bios.query('born_city == "Jersey City" & born_country == "USA"')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
16442,16558,Don Sheldon,1930-05-26,Jersey City,New Jersey,USA,United States,NaN,NaN,2015-06-11
20238,20382,Bill Boddington,1910-11-22,Jersey City,New Jersey,USA,United States,NaN,NaN,1996-11-15
20871,21018,Evelyn Terhune,1932-07-21,Jersey City,New Jersey,USA,United States,165.0,52.0,1981-06-08
23526,23708,Ernest Gignoux,1874-08-26,Jersey City,New Jersey,USA,United States,NaN,NaN,1955-09-14
23550,23733,Marty Lang,1949-05-20,Jersey City,New Jersey,USA,United States,183.0,75.0,NaN
31110,31346,Don Holder,1928-09-29,Jersey City,New Jersey,USA,United States,NaN,NaN,2015-09-01
32772,33018,Bob Sparks,1947-09-11,Jersey City,New Jersey,USA,United States,191.0,84.0,NaN
44369,44710,Bill Libbey,1855-03-27,Jersey City,New Jersey,USA,United States,NaN,NaN,1927-09-06
50741,51100,Lisa Lindstrom,1912-08-07,Jersey City,New Jersey,USA,United States,NaN,NaN,1994-06-22
60362,60795,Alexander Weyand,1892-01-10,Jersey City,New Jersey,USA,United States,NaN,NaN,1982-05-10
60368,60801,Henry Wittenberg,1918-09-18,Jersey City,New Jersey,USA,United States,NaN,NaN,2010-03-09
78327,78918,Edwin Pritchard,1889-05-17,Jersey City,New Jersey,USA,United States,185.0,72.0,1976-04-03
78360,78951,Frank Riley,1887-07-03,Jersey City,New Jersey,USA,United States,185.0,78.0,1950-10-30
82915,83573,"John Amabile, Jr.",1962-04-23,Jersey City,New Jersey,USA,Puerto Rico,188.0,98.0,NaN
94955,95722,William Nagle,1885-05-09,Jersey City,New Jersey,USA,United States,NaN,NaN,1970-04-10
116245,117631,Sunitha Rao,1985-10-27,Jersey City,New Jersey,USA,India,170.0,63.0,NaN

In [55]:
bios.query('born_city == "Edison" & born_country == "USA"')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
113704,115003,Erison Hurtault,1984-12-29,Edison,New Jersey,USA,Dominica,178.0,78.0,NaN

In [147]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [148]:
coffee['price'] = 5.99

In [154]:
coffee['new_price'] = np.where(coffee['Coffee Type'] == 'Espresso', 3.99, 5.99)

In [155]:
coffee

          Day Coffee Type  Units Sold  price  new_price
0      Monday    Espresso          25   5.99       3.99
1      Monday       Latte          15   5.99       5.99
2     Tuesday    Espresso          30   5.99       3.99
3     Tuesday       Latte          20   5.99       5.99
4   Wednesday    Espresso          35   5.99       3.99
5   Wednesday       Latte          25   5.99       5.99
6    Thursday    Espresso          40   5.99       3.99
7    Thursday       Latte          30   5.99       5.99
8      Friday    Espresso          45   5.99       3.99
9      Friday       Latte          35   5.99       5.99
10   Saturday    Espresso          45   5.99       3.99
11   Saturday       Latte          35   5.99       5.99
12     Sunday    Espresso          45   5.99       3.99
13     Sunday       Latte          35   5.99       5.99

In [166]:
coffee

          Day Coffee Type  Units Sold  new_price
0      Monday    Espresso          25       3.99
1      Monday       Latte          15       5.99
2     Tuesday    Espresso          30       3.99
3     Tuesday       Latte          20       5.99
4   Wednesday    Espresso          35       3.99
5   Wednesday       Latte          25       5.99
6    Thursday    Espresso          40       3.99
7    Thursday       Latte          30       5.99
8      Friday    Espresso          45       3.99
9      Friday       Latte          35       5.99
10   Saturday    Espresso          45       3.99
11   Saturday       Latte          35       5.99
12     Sunday    Espresso          45       3.99
13     Sunday       Latte          35       5.99

In [164]:
# coffee.drop(columns = ['price'])

In [167]:
# coffee.drop(columns = ['price'], inplace=True)
# coffee

In [168]:
# coffee = coffee[['Coffee Type', 'Units Sold']]
coffee

          Day Coffee Type  Units Sold  new_price
0      Monday    Espresso          25       3.99
1      Monday       Latte          15       5.99
2     Tuesday    Espresso          30       3.99
3     Tuesday       Latte          20       5.99
4   Wednesday    Espresso          35       3.99
5   Wednesday       Latte          25       5.99
6    Thursday    Espresso          40       3.99
7    Thursday       Latte          30       5.99
8      Friday    Espresso          45       3.99
9      Friday       Latte          35       5.99
10   Saturday    Espresso          45       3.99
11   Saturday       Latte          35       5.99
12     Sunday    Espresso          45       3.99
13     Sunday       Latte          35       5.99

In [169]:
coffee

          Day Coffee Type  Units Sold  new_price
0      Monday    Espresso          25       3.99
1      Monday       Latte          15       5.99
2     Tuesday    Espresso          30       3.99
3     Tuesday       Latte          20       5.99
4   Wednesday    Espresso          35       3.99
5   Wednesday       Latte          25       5.99
6    Thursday    Espresso          40       3.99
7    Thursday       Latte          30       5.99
8      Friday    Espresso          45       3.99
9      Friday       Latte          35       5.99
10   Saturday    Espresso          45       3.99
11   Saturday       Latte          35       5.99
12     Sunday    Espresso          45       3.99
13     Sunday       Latte          35       5.99

In [171]:
coffee['revenue'] = coffee['Units Sold'] * coffee['new_price']

In [172]:
coffee

          Day Coffee Type  Units Sold  new_price  revenue
0      Monday    Espresso          25       3.99    99.75
1      Monday       Latte          15       5.99    89.85
2     Tuesday    Espresso          30       3.99   119.70
3     Tuesday       Latte          20       5.99   119.80
4   Wednesday    Espresso          35       3.99   139.65
5   Wednesday       Latte          25       5.99   149.75
6    Thursday    Espresso          40       3.99   159.60
7    Thursday       Latte          30       5.99   179.70
8      Friday    Espresso          45       3.99   179.55
9      Friday       Latte          35       5.99   209.65
10   Saturday    Espresso          45       3.99   179.55
11   Saturday       Latte          35       5.99   209.65
12     Sunday    Espresso          45       3.99   179.55
13     Sunday       Latte          35       5.99   209.65

In [173]:
coffee.rename(columns={'new_price': 'price'}, inplace=True)

In [174]:
coffee = coffee.rename(columns={'new_price': 'price'})

In [175]:
coffee

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso          25   3.99    99.75
1      Monday       Latte          15   5.99    89.85
2     Tuesday    Espresso          30   3.99   119.70
3     Tuesday       Latte          20   5.99   119.80
4   Wednesday    Espresso          35   3.99   139.65
5   Wednesday       Latte          25   5.99   149.75
6    Thursday    Espresso          40   3.99   159.60
7    Thursday       Latte          30   5.99   179.70
8      Friday    Espresso          45   3.99   179.55
9      Friday       Latte          35   5.99   209.65
10   Saturday    Espresso          45   3.99   179.55
11   Saturday       Latte          35   5.99   209.65
12     Sunday    Espresso          45   3.99   179.55
13     Sunday       Latte          35   5.99   209.65

In [71]:
bios_new = bios.copy()

In [72]:
bios_new['first_name'] = bios_new['name'].str.split(' ').str[0]

In [73]:
bios_new

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert
...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Polina
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Valeriya
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Yuliya
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,André
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Bill

In [74]:
bios_new.query('first_name == "Harun"')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name
59884,60312,Harun Doğan,1976-01-01,Kahramanmaraş,Kahramanmaraş,TUR,Türkiye,165.0,58.0,NaN,Harun
63220,63690,Harun Ülman,1900-07-11,NaN,NaN,NaN,Türkiye,NaN,NaN,1977-01-26,Harun

In [75]:
bios_new['born_datetime'] = pd.to_datetime(bios_new['born_date'])

In [76]:
bios_new

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17
...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Polina,2002-01-30
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Valeriya,1999-09-20
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Yuliya,1998-05-08
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,André,1899-05-19
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Bill,1913-07-15

In [77]:
bios_new['born_year'] = bios_new['born_datetime'].dt.year

In [78]:
bios_new[['name', 'born_year']]

                         name  born_year
0       Jean-François Blanchy     1886.0
1              Arnaud Boetsch     1969.0
2                Jean Borotra     1898.0
3             Jacques Brugnon     1895.0
4                Albert Canet     1878.0
...                       ...        ...
145495      Polina Luchnikova     2002.0
145496    Valeriya Merkusheva     1999.0
145497        Yuliya Smirnova     1998.0
145498         André Foussard     1899.0
145499          Bill Phillips     1913.0

[145500 rows x 2 columns]

In [79]:
bios_new.to_csv('/bios_new.csv', index = False)

In [80]:
bios_new['height_category'] = bios_new['height_cm'].apply(lambda x: 'Short' if x < 165 else ('Average' if x < 185 else 'Tall') )

In [81]:
bios_new

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime,born_year,height_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0,Tall
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0,Average
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13,1898.0,Average
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895.0,Average
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17,1878.0,Tall
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Polina,2002-01-30,2002.0,Average
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Valeriya,1999-09-20,1999.0,Average
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Yuliya,1998-05-08,1998.0,Short
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,André,1899-05-19,1899.0,Average
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Bill,1913-07-15,1913.0,Tall

In [82]:
def categorize_athlete(row):
  if row['height_cm'] < 175 and row['weight_kg'] < 70:
    return 'Lightweight'
  elif row['height_cm'] < 185 and row['weight_kg'] <= 80:
    return 'Middleweight'
  else:
    return 'Heavyweight'


bios_new['category'] = bios_new.apply(categorize_athlete, axis=1)

In [83]:
bios_new

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime,born_year,height_category,category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0,Tall,Heavyweight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0,Average,Middleweight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13,1898.0,Average,Middleweight
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895.0,Average,Lightweight
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17,1878.0,Tall,Heavyweight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Polina,2002-01-30,2002.0,Average,Lightweight
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Valeriya,1999-09-20,1999.0,Average,Lightweight
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Yuliya,1998-05-08,1998.0,Short,Lightweight
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,André,1899-05-19,1899.0,Average,Heavyweight
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Bill,1913-07-15,1913.0,Tall,Heavyweight

In [84]:
nocs = pd.read_csv('/noc_regions.csv')

In [85]:
nocs

     NOC       region                 notes
0    AFG  Afghanistan                   NaN
1    AHO      Curacao  Netherlands Antilles
2    ALB      Albania                   NaN
3    ALG      Algeria                   NaN
4    AND      Andorra                   NaN
..   ...          ...                   ...
225  YEM        Yemen                   NaN
226  YMD        Yemen           South Yemen
227  YUG       Serbia            Yugoslavia
228  ZAM       Zambia                   NaN
229  ZIM     Zimbabwe                   NaN

[230 rows x 3 columns]

In [86]:
bios_new = pd.merge(bios, nocs, left_on='born_country', right_on='NOC', how='left')

In [87]:
bios_new

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,NOC_y,region,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,FRA,France,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,GBR,UK,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,RUS,Russia,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,RUS,Russia,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,RUS,Russia,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,FRA,France,NaN
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,AUS,Australia,NaN

In [88]:
bios_new.rename(columns={'region': 'born_full_country'}, inplace=True)

In [89]:
bios_new

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,NOC_y,born_full_country,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,FRA,France,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,GBR,UK,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,RUS,Russia,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,RUS,Russia,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,RUS,Russia,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,FRA,France,NaN
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,AUS,Australia,NaN

In [90]:
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,NOC_y,born_full_country,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,FRA,France,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,GBR,UK,NaN

In [91]:
bios_new[bios_new['NOC_x'] != bios_new['born_full_country']][['name', 'NOC_x', 'born_full_country']]

                       name    NOC_x born_full_country
4              Albert Canet   France                UK
12                J. Defert   France               NaN
13           Étienne Durand   France               NaN
16               Guy Forget   France           Morocco
27       Guy, Baron Lejeune   France               NaN
...                     ...      ...               ...
145491        Matthew Wepke  Jamaica               NaN
145493   Landysh Falyakhova      ROC            Russia
145495    Polina Luchnikova      ROC            Russia
145496  Valeriya Merkusheva      ROC            Russia
145497      Yuliya Smirnova      ROC            Russia

[73210 rows x 3 columns]

In [92]:
usa = bios_new[bios_new['born_country'] == 'USA'].copy()

In [93]:
gbr = bios_new[bios_new['born_country'] == 'GBR'].copy()

In [94]:
usa.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,NOC_y,born_full_country,notes
54,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN,USA,USA,NaN
960,964,Xóchitl Escobedo,1968-09-17,West Covina,California,USA,Mexico,170.0,60.0,NaN,USA,USA,NaN
961,965,Angélica Gavaldón,1973-10-03,El Centro,California,USA,Mexico,160.0,54.0,NaN,USA,USA,NaN
1231,1238,Bert Schneider,1897-07-01,Cleveland,Ohio,USA,Canada,NaN,NaN,1986-02-20,USA,USA,NaN
1345,1352,Laura Berg,1975-01-06,Santa Fe Springs,California,USA,United States,168.0,61.0,NaN,USA,USA,NaN

In [95]:
gbr.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,NOC_y,born_full_country,notes
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,GBR,UK,NaN
37,38,Helen Aitchison,1881-12-06,Sunderland,England,GBR,Great Britain,NaN,NaN,1947-05-26,GBR,UK,NaN
38,39,Geraldine Beamish,1883-06-23,Forest Gate,England,GBR,Great Britain,NaN,NaN,1972-05-10,GBR,UK,NaN
39,40,Dora Boothby,1881-08-02,Finchley,England,GBR,Great Britain,NaN,NaN,1970-02-22,GBR,UK,NaN
40,41,Julie Bradbury,1967-02-12,Oxford,England,GBR,Great Britain,175.0,64.0,NaN,GBR,UK,NaN

In [96]:
new_df = pd.concat([usa, gbr])

In [97]:
new_df.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,NOC_y,born_full_country,notes
54,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN,USA,USA,NaN
960,964,Xóchitl Escobedo,1968-09-17,West Covina,California,USA,Mexico,170.0,60.0,NaN,USA,USA,NaN
961,965,Angélica Gavaldón,1973-10-03,El Centro,California,USA,Mexico,160.0,54.0,NaN,USA,USA,NaN
1231,1238,Bert Schneider,1897-07-01,Cleveland,Ohio,USA,Canada,NaN,NaN,1986-02-20,USA,USA,NaN
1345,1352,Laura Berg,1975-01-06,Santa Fe Springs,California,USA,United States,168.0,61.0,NaN,USA,USA,NaN

In [98]:
results

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,17.0,True,None
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,None
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,32.0,True,None
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,None
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,None
...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,None,26.0,False,None
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,None,28.0,False,None
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,None
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,None,NaN,False,None
308407,2022.0,Winter,None,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,None,None,24.0,False,None

In [99]:
combined_df = pd.merge(results, bios, on="athlete_id", how='left')

In [100]:
combined_df

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,17.0,True,None,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,None,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,32.0,True,None,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,None,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,None,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,None,26.0,False,None,Marián Skupek,2001-07-12,Gelnica,Košice,SVK,Slovakia,196.0,108.0,NaN
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,None,28.0,False,None,Elsa Fermbäck,1998-03-28,Vemdalen,Jämtland,SWE,Sweden,NaN,NaN,NaN
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,None,Hilma Lövblom,2000-08-16,Täby,Stockholm,SWE,Sweden,NaN,NaN,NaN
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,None,NaN,False,None,Hilma Lövblom,2000-08-16,Täby,Stockholm,SWE,Sweden,NaN,NaN,NaN
308407,2022.0,Winter,None,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,None,None,24.0,False,None,Charlotta Säfvenberg,1994-10-07,Kungsbacka,Halland,SWE,Sweden,NaN,NaN,NaN

In [176]:
coffee

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso          25   3.99    99.75
1      Monday       Latte          15   5.99    89.85
2     Tuesday    Espresso          30   3.99   119.70
3     Tuesday       Latte          20   5.99   119.80
4   Wednesday    Espresso          35   3.99   139.65
5   Wednesday       Latte          25   5.99   149.75
6    Thursday    Espresso          40   3.99   159.60
7    Thursday       Latte          30   5.99   179.70
8      Friday    Espresso          45   3.99   179.55
9      Friday       Latte          35   5.99   209.65
10   Saturday    Espresso          45   3.99   179.55
11   Saturday       Latte          35   5.99   209.65
12     Sunday    Espresso          45   3.99   179.55
13     Sunday       Latte          35   5.99   209.65

In [183]:
coffee.loc[0:1, 'Units Sold'] = np.nan

In [184]:
coffee

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso         NaN   3.99    99.75
1      Monday       Latte         NaN   5.99    89.85
2     Tuesday    Espresso         NaN   3.99   119.70
3     Tuesday       Latte        20.0   5.99   119.80
4   Wednesday    Espresso        35.0   3.99   139.65
5   Wednesday       Latte        25.0   5.99   149.75
6    Thursday    Espresso        40.0   3.99   159.60
7    Thursday       Latte        30.0   5.99   179.70
8      Friday    Espresso        45.0   3.99   179.55
9      Friday       Latte        35.0   5.99   209.65
10   Saturday    Espresso        45.0   3.99   179.55
11   Saturday       Latte        35.0   5.99   209.65
12     Sunday    Espresso        45.0   3.99   179.55
13     Sunday       Latte        35.0   5.99   209.65

In [192]:
coffee.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Day          14 non-null     object
 1   Coffee Type  14 non-null     object
 2   Units Sold   10 non-null     float64
 3   price        14 non-null     float64
 4   revenue      14 non-null     float64
dtypes: float64(3), object(2)
memory usage: 692.0+ bytes

In [193]:
coffee.isna().sum()

Day            0
Coffee Type    0
Units Sold     4
price          0
revenue        0
dtype: int64

In [194]:
coffee.fillna(1000)

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso      1000.0   3.99    99.75
1      Monday       Latte      1000.0   5.99    89.85
2     Tuesday    Espresso      1000.0   3.99   119.70
3     Tuesday       Latte      1000.0   5.99   119.80
4   Wednesday    Espresso        35.0   3.99   139.65
5   Wednesday       Latte        25.0   5.99   149.75
6    Thursday    Espresso        40.0   3.99   159.60
7    Thursday       Latte        30.0   5.99   179.70
8      Friday    Espresso        45.0   3.99   179.55
9      Friday       Latte        35.0   5.99   209.65
10   Saturday    Espresso        45.0   3.99   179.55
11   Saturday       Latte        35.0   5.99   209.65
12     Sunday    Espresso        45.0   3.99   179.55
13     Sunday       Latte        35.0   5.99   209.65

In [197]:
coffee.fillna(coffee['Units Sold'].mean())

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso        37.0   3.99    99.75
1      Monday       Latte        37.0   5.99    89.85
2     Tuesday    Espresso        37.0   3.99   119.70
3     Tuesday       Latte        37.0   5.99   119.80
4   Wednesday    Espresso        35.0   3.99   139.65
5   Wednesday       Latte        25.0   5.99   149.75
6    Thursday    Espresso        40.0   3.99   159.60
7    Thursday       Latte        30.0   5.99   179.70
8      Friday    Espresso        45.0   3.99   179.55
9      Friday       Latte        35.0   5.99   209.65
10   Saturday    Espresso        45.0   3.99   179.55
11   Saturday       Latte        35.0   5.99   209.65
12     Sunday    Espresso        45.0   3.99   179.55
13     Sunday       Latte        35.0   5.99   209.65

In [189]:
# coffee.loc[[2, 3], 'Units Sold'] = np.nan

In [201]:
coffee.loc[0:1, ['Units Sold']] = 15

In [199]:
# coffee['Units Sold'] = coffee['Units Sold'].interpolate()

In [202]:
coffee

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso   15.000000   3.99    99.75
1      Monday       Latte   15.000000   5.99    89.85
2     Tuesday    Espresso   21.666667   3.99   119.70
3     Tuesday       Latte   28.333333   5.99   119.80
4   Wednesday    Espresso   35.000000   3.99   139.65
5   Wednesday       Latte   25.000000   5.99   149.75
6    Thursday    Espresso   40.000000   3.99   159.60
7    Thursday       Latte   30.000000   5.99   179.70
8      Friday    Espresso   45.000000   3.99   179.55
9      Friday       Latte   35.000000   5.99   209.65
10   Saturday    Espresso   45.000000   3.99   179.55
11   Saturday       Latte   35.000000   5.99   209.65
12     Sunday    Espresso   45.000000   3.99   179.55
13     Sunday       Latte   35.000000   5.99   209.65

In [203]:
coffee[coffee['Units Sold'].notna()]

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso   15.000000   3.99    99.75
1      Monday       Latte   15.000000   5.99    89.85
2     Tuesday    Espresso   21.666667   3.99   119.70
3     Tuesday       Latte   28.333333   5.99   119.80
4   Wednesday    Espresso   35.000000   3.99   139.65
5   Wednesday       Latte   25.000000   5.99   149.75
6    Thursday    Espresso   40.000000   3.99   159.60
7    Thursday       Latte   30.000000   5.99   179.70
8      Friday    Espresso   45.000000   3.99   179.55
9      Friday       Latte   35.000000   5.99   209.65
10   Saturday    Espresso   45.000000   3.99   179.55
11   Saturday       Latte   35.000000   5.99   209.65
12     Sunday    Espresso   45.000000   3.99   179.55
13     Sunday       Latte   35.000000   5.99   209.65

In [204]:
coffee[coffee['Units Sold'].isna()]

Empty DataFrame
Columns: [Day, Coffee Type, Units Sold, price, revenue]
Index: []

In [205]:
coffee.dropna()

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso   15.000000   3.99    99.75
1      Monday       Latte   15.000000   5.99    89.85
2     Tuesday    Espresso   21.666667   3.99   119.70
3     Tuesday       Latte   28.333333   5.99   119.80
4   Wednesday    Espresso   35.000000   3.99   139.65
5   Wednesday       Latte   25.000000   5.99   149.75
6    Thursday    Espresso   40.000000   3.99   159.60
7    Thursday       Latte   30.000000   5.99   179.70
8      Friday    Espresso   45.000000   3.99   179.55
9      Friday       Latte   35.000000   5.99   209.65
10   Saturday    Espresso   45.000000   3.99   179.55
11   Saturday       Latte   35.000000   5.99   209.65
12     Sunday    Espresso   45.000000   3.99   179.55
13     Sunday       Latte   35.000000   5.99   209.65

In [115]:
bios['born_city'].value_counts()

born_city
Budapest           1378
Moskva (Moscow)     883
Oslo                708
Stockholm           629
Praha (Prague)      600
                   ...
Bodrogkisfalud        1
Ternberg              1
Klaus                 1
Plaški                1
Dulwich Hill          1
Name: count, Length: 22368, dtype: int64

In [116]:
bios[bios['born_country'] == 'USA']['born_region'].value_counts()

born_region
California              1634
New York                 990
Illinois                 585
Pennsylvania             530
Massachusetts            530
New Jersey               381
Texas                    368
Minnesota                365
Ohio                     328
Michigan                 319
Washington               240
Florida                  235
Wisconsin                209
Colorado                 207
Connecticut              156
Indiana                  150
Oregon                   132
Georgia                  129
Virginia                 121
Maryland                 117
District of Columbia     107
Iowa                     102
Hawaiʻi                   95
Kansas                    94
Oklahoma                  93
Louisiana                 92
Utah                      91
Missouri                  91
North Carolina            86
Arizona                   83
New Hampshire             83
Vermont                   68
Mississippi               66
Alabama                   64
Kentucky                  62
Tennessee                 62
Nebraska                  60
Rhode Island              56
Montana                   55
South Carolina            50
Maine                     50
Alaska                    45
Arkansas                  42
Idaho                     41
New Mexico                38
Nevada                    36
South Dakota              27
West Virginia             24
Delaware                  22
North Dakota              16
Wyoming                   14
Name: count, dtype: int64

In [206]:
coffee

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso   15.000000   3.99    99.75
1      Monday       Latte   15.000000   5.99    89.85
2     Tuesday    Espresso   21.666667   3.99   119.70
3     Tuesday       Latte   28.333333   5.99   119.80
4   Wednesday    Espresso   35.000000   3.99   139.65
5   Wednesday       Latte   25.000000   5.99   149.75
6    Thursday    Espresso   40.000000   3.99   159.60
7    Thursday       Latte   30.000000   5.99   179.70
8      Friday    Espresso   45.000000   3.99   179.55
9      Friday       Latte   35.000000   5.99   209.65
10   Saturday    Espresso   45.000000   3.99   179.55
11   Saturday       Latte   35.000000   5.99   209.65
12     Sunday    Espresso   45.000000   3.99   179.55
13     Sunday       Latte   35.000000   5.99   209.65

In [207]:
# coffee.rename(columns={'new_price': 'price'})

In [208]:
coffee.groupby(['Coffee Type']).agg({'Units Sold': 'sum', 'price':'mean'})

             Units Sold  price
Coffee Type
Espresso     246.666667   3.99
Latte        203.333333   5.99

In [209]:
coffee

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso   15.000000   3.99    99.75
1      Monday       Latte   15.000000   5.99    89.85
2     Tuesday    Espresso   21.666667   3.99   119.70
3     Tuesday       Latte   28.333333   5.99   119.80
4   Wednesday    Espresso   35.000000   3.99   139.65
5   Wednesday       Latte   25.000000   5.99   149.75
6    Thursday    Espresso   40.000000   3.99   159.60
7    Thursday       Latte   30.000000   5.99   179.70
8      Friday    Espresso   45.000000   3.99   179.55
9      Friday       Latte   35.000000   5.99   209.65
10   Saturday    Espresso   45.000000   3.99   179.55
11   Saturday       Latte   35.000000   5.99   209.65
12     Sunday    Espresso   45.000000   3.99   179.55
13     Sunday       Latte   35.000000   5.99   209.65

In [210]:
pivot = coffee.pivot(columns = 'Coffee Type', index='Day', values='revenue')

In [211]:
pivot

Coffee Type  Espresso   Latte
Day
Friday         179.55  209.65
Monday          99.75   89.85
Saturday       179.55  209.65
Sunday         179.55  209.65
Thursday       159.60  179.70
Tuesday        119.70  119.80
Wednesday      139.65  149.75

In [212]:
pivot.sum()

Coffee Type
Espresso    1057.35
Latte       1168.05
dtype: float64

In [213]:
pivot.loc['Monday', 'Latte']

89.85000000000001

In [214]:
pivot.sum(axis=1)

Day
Friday       389.2
Monday       189.6
Saturday     389.2
Sunday       389.2
Thursday     339.3
Tuesday      239.5
Wednesday    289.4
dtype: float64

In [215]:
bios['born_date'] = pd.to_datetime(bios['born_date'])

In [216]:
bios['born_date']

0        1886-12-12
1        1969-04-01
2        1898-08-13
3        1895-05-11
4        1878-04-17
            ...
145495   2002-01-30
145496   1999-09-20
145497   1998-05-08
145498   1899-05-19
145499   1913-07-15
Name: born_date, Length: 145500, dtype: datetime64[ns]

In [217]:
bios.groupby(bios['born_date'].dt.year).count()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
born_date,,,,,,,,,,
1828.0,1,1,1,1,1,1,1,0,0,1
1831.0,2,2,2,2,2,2,2,0,0,2
1833.0,1,1,1,1,1,1,1,0,0,1
1836.0,1,1,1,1,1,1,1,0,0,1
1837.0,1,1,1,1,1,1,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...
2005.0,163,163,163,64,64,64,163,13,12,1
2006.0,17,17,17,8,8,8,17,1,0,0
2007.0,3,3,3,1,1,1,3,0,0,0
2008.0,3,3,3,2,2,2,3,1,1,0
2009.0,1,1,1,1,1,1,1,0,0,0

In [218]:
bios.groupby(bios['born_date'].dt.year)['name'].count().reset_index().sort_values('name', ascending=False)

     born_date  name
139     1972.0  2231
152     1985.0  2227
140     1973.0  2216
138     1971.0  2205
137     1970.0  2174
..         ...   ...
5       1838.0     1
4       1837.0     1
3       1836.0     1
2       1833.0     1
176     2009.0     1

[177 rows x 2 columns]

In [219]:
bios['month_born'] = bios['born_date'].dt.month

In [220]:
bios['year_born'] = bios['born_date'].dt.year

In [221]:
bios.groupby([bios['year_born'], bios['month_born']])['name'].count().reset_index().sort_values('name', ascending=False)

      year_born  month_born  name
1437     1970.0         1.0   239
1461     1972.0         1.0   229
1629     1986.0         1.0   227
1497     1975.0         1.0   227
1617     1985.0         1.0   225
...         ...         ...   ...
95       1857.0         5.0     1
96       1857.0         7.0     1
97       1857.0         8.0     1
98       1857.0         9.0     1
1884     2009.0         1.0     1

[1885 rows x 3 columns]

In [230]:
bios['height_rank'] = bios['height_cm'].rank(ascending=False)

In [231]:
bios

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,month_born,year_born,height_rank
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,12.0,1886.0,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,4.0,1969.0,27597.5
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,8.0,1898.0,27597.5
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,5.0,1895.0,83975.0
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,4.0,1878.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,1.0,2002.0,87188.5
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,9.0,1999.0,83975.0
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,5.0,1998.0,96305.5
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,5.0,1899.0,89274.5
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,7.0,1913.0,NaN

In [243]:
bios.sort_values(['height_rank']).sample(10)[['name','height_rank']]

                      name  height_rank
73394       Ifeoma Mbanugo      81027.5
18072            John Rahm          NaN
104386        Corinne Raux      94490.0
114582        Serhiy Breus       6946.0
51942          Andrea Heim      58380.5
115498      Valeriya Yegay      89274.5
47845        József Katona      54014.0
50271       Hakan Eskioğlu       9882.0
94834         Petsch Moser       9882.0
106946  Aleksey Krupnyakov      54014.0

In [244]:
coffee.head()

         Day Coffee Type  Units Sold  price  revenue
0     Monday    Espresso   15.000000   3.99    99.75
1     Monday       Latte   15.000000   5.99    89.85
2    Tuesday    Espresso   21.666667   3.99   119.70
3    Tuesday       Latte   28.333333   5.99   119.80
4  Wednesday    Espresso   35.000000   3.99   139.65

In [245]:
coffee['cum_revenue'] = coffee['revenue'].cumsum()

In [246]:
coffee

          Day Coffee Type  Units Sold  price  revenue  cum_revenue
0      Monday    Espresso   15.000000   3.99    99.75        99.75
1      Monday       Latte   15.000000   5.99    89.85       189.60
2     Tuesday    Espresso   21.666667   3.99   119.70       309.30
3     Tuesday       Latte   28.333333   5.99   119.80       429.10
4   Wednesday    Espresso   35.000000   3.99   139.65       568.75
5   Wednesday       Latte   25.000000   5.99   149.75       718.50
6    Thursday    Espresso   40.000000   3.99   159.60       878.10
7    Thursday       Latte   30.000000   5.99   179.70      1057.80
8      Friday    Espresso   45.000000   3.99   179.55      1237.35
9      Friday       Latte   35.000000   5.99   209.65      1447.00
10   Saturday    Espresso   45.000000   3.99   179.55      1626.55
11   Saturday       Latte   35.000000   5.99   209.65      1836.20
12     Sunday    Espresso   45.000000   3.99   179.55      2015.75
13     Sunday       Latte   35.000000   5.99   209.65      2225.40

In [249]:
coffee['yesterday_revenue'] = coffee['revenue'].shift(2)

In [250]:
coffee

,Day,Coffee Type,Units Sold,price,revenue,cum_revenue,yesterday_revenue
0,Monday,Espresso,15.000000,3.99,99.75,99.75,NaN
1,Monday,Latte,15.000000,5.99,89.85,189.60,NaN
2,Tuesday,Espresso,21.666667,3.99,119.70,309.30,99.75
3,Tuesday,Latte,28.333333,5.99,119.80,429.10,89.85
4,Wednesday,Espresso,35.000000,3.99,139.65,568.75,119.70
5,Wednesday,Latte,25.000000,5.99,149.75,718.50,119.80
6,Thursday,Espresso,40.000000,3.99,159.60,878.10,139.65
7,Thursday,Latte,30.000000,5.99,179.70,1057.80,149.75
8,Friday,Espresso,45.000000,3.99,179.55,1237.35,159.60
9,Friday,Latte,35.000000,5.99,209.65,1447.00,179.70
10,Saturday,Espresso,45.000000,3.99,179.55,1626.55,179.55
11,Saturday,Latte,35.000000,5.99,209.65,1836.20,209.65
12,Sunday,Espresso,45.000000,3.99,179.55,2015.75,179.55
13,Sunday,Latte,35.000000,5.99,209.65,2225.40,209.65

In [257]:
coffee['per_change'] = coffee['revenue'] / coffee['yesterday_revenue'] * 100

In [258]:
coffee

,Day,Coffee Type,Units Sold,price,revenue,cum_revenue,yesterday_revenue,per_change
0,Monday,Espresso,15.000000,3.99,99.75,99.75,NaN,NaN
1,Monday,Latte,15.000000,5.99,89.85,189.60,NaN,NaN
2,Tuesday,Espresso,21.666667,3.99,119.70,309.30,99.75,120.000000
3,Tuesday,Latte,28.333333,5.99,119.80,429.10,89.85,133.333333
4,Wednesday,Espresso,35.000000,3.99,139.65,568.75,119.70,116.666667
5,Wednesday,Latte,25.000000,5.99,149.75,718.50,119.80,125.000000
6,Thursday,Espresso,40.000000,3.99,159.60,878.10,139.65,114.285714
7,Thursday,Latte,30.000000,5.99,179.70,1057.80,149.75,120.000000
8,Friday,Espresso,45.000000,3.99,179.55,1237.35,159.60,112.500000
9,Friday,Latte,35.000000,5.99,209.65,1447.00,179.70,116.666667
10,Saturday,Espresso,45.000000,3.99,179.55,1626.55,179.55,100.000000
11,Saturday,Latte,35.000000,5.99,209.65,1836.20,209.65,100.000000
12,Sunday,Espresso,45.000000,3.99,179.55,2015.75,179.55,100.000000
13,Sunday,Latte,35.000000,5.99,209.65,2225.40,209.65,100.000000

In [259]:
latte = coffee[coffee['Coffee Type'] == 'Latte'].copy()

In [260]:
latte.head()

,Day,Coffee Type,Units Sold,price,revenue,cum_revenue,yesterday_revenue,per_change
1,Monday,Latte,15.000000,5.99,89.85,189.6,NaN,NaN
3,Tuesday,Latte,28.333333,5.99,119.80,429.1,89.85,133.333333
5,Wednesday,Latte,25.000000,5.99,149.75,718.5,119.80,125.000000
7,Thursday,Latte,30.000000,5.99,179.70,1057.8,149.75,120.000000
9,Friday,Latte,35.000000,5.99,209.65,1447.0,179.70,116.666667

In [263]:
latte['3days'] = latte['Units Sold'].rolling(4).sum()

In [264]:
latte

,Day,Coffee Type,Units Sold,price,revenue,cum_revenue,yesterday_revenue,per_change,3days
1,Monday,Latte,15.000000,5.99,89.85,189.6,NaN,NaN,NaN
3,Tuesday,Latte,28.333333,5.99,119.80,429.1,89.85,133.333333,NaN
5,Wednesday,Latte,25.000000,5.99,149.75,718.5,119.80,125.000000,NaN
7,Thursday,Latte,30.000000,5.99,179.70,1057.8,149.75,120.000000,98.333333
9,Friday,Latte,35.000000,5.99,209.65,1447.0,179.70,116.666667,118.333333
11,Saturday,Latte,35.000000,5.99,209.65,1836.2,209.65,100.000000,125.000000
13,Sunday,Latte,35.000000,5.99,209.65,2225.4,209.65,100.000000,135.000000

In [266]:
pd.__version__

'2.2.2'

In [267]:
result_numpy = pd.read_csv('/results.csv')

In [268]:
result_arrow = pd.read_csv('/results.csv', engine='pyarrow', dtype_backend='pyarrow')

In [269]:
result_numpy

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,NaN
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,NaN
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,NaN
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,NaN
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,NaN

In [270]:
result_arrow

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,<NA>,17.0,True,<NA>
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,<NA>,False,<NA>
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,<NA>,32.0,True,<NA>
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,<NA>
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,<NA>
...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,<NA>,26.0,False,<NA>
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,<NA>,28.0,False,<NA>
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,<NA>
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,<NA>,<NA>,False,<NA>
308407,2022.0,Winter,<NA>,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,<NA>,<NA>,24.0,False,<NA>

In [271]:
result_numpy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 308408 entries, 0 to 308407
Data columns (total 11 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   year        305807 non-null  float64
 1   type        305807 non-null  object
 2   discipline  308407 non-null  object
 3   event       308408 non-null  object
 4   as          308408 non-null  object
 5   athlete_id  308408 non-null  int64
 6   noc         308407 non-null  object
 7   team        121714 non-null  object
 8   place       283193 non-null  float64
 9   tied        308408 non-null  bool
 10  medal       44139 non-null   object
dtypes: bool(1), float64(2), int64(1), object(7)
memory usage: 23.8+ MB

In [272]:
result_arrow.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 308408 entries, 0 to 308407
Data columns (total 11 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   year        305807 non-null  double[pyarrow]
 1   type        305807 non-null  string[pyarrow]
 2   discipline  308407 non-null  string[pyarrow]
 3   event       308408 non-null  string[pyarrow]
 4   as          308408 non-null  string[pyarrow]
 5   athlete_id  308408 non-null  int64[pyarrow]
 6   noc         308407 non-null  string[pyarrow]
 7   team        121714 non-null  string[pyarrow]
 8   place       283193 non-null  double[pyarrow]
 9   tied        308408 non-null  bool[pyarrow]
 10  medal       44139 non-null   string[pyarrow]
dtypes: bool[pyarrow](1), double[pyarrow](2), int64[pyarrow](1), string[pyarrow](7)
memory usage: 37.5 MB